services:
  web:
    build:
      dockerfile: Dockerfile
    command: ["ng", "serve","--hmr","--poll", "500", "--host", "0.0.0.0"]
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    ports:
      - "4200:4200"
